from typing import Dict, Any, List
import json
import logging

class LLMPlanner:
    """
    An LLM-based planner for decomposing queries into sub-tasks.
    For this implementation, we use a HuggingFace pipeline (flan-t5-small) to demonstrate
    an open-source local inference approach. In production, you would swap this for a 
    larger model (Llama-3, Mistral) or a cloud API (OpenAI, Gemini).
    """
    def __init__(self, model_name: str = "google/flan-t5-base"):
        print(f"Initializing LLMPlanner with model: {model_name}")
        try:
            from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
            logging.getLogger("transformers").setLevel(logging.ERROR)
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
            self.model_loaded = True
        except ImportError:
            print("Warning: transformers library not found. Running in fallback mode.")
            self.model_loaded = False
        except Exception as e:
            print(f"Warning: Failed to load model {model_name} due to: {e}. Running in fallback mode.")
            self.model_loaded = False
    
    def plan(self, query: str) -> Dict[str, Any]:
        if not self.model_loaded:
            return self._fallback_plan(query)
            
        prompt = f"""Decompose the following user query into a logical sequence of subtasks.
Query: "{query}"
Subtask types can be: 'retrieve', 'reason', or 'execute'.
Output the plan in valid JSON format with 'goal', 'subtasks', and 'required_tools'.
JSON Output:"""
        
        try:
            # Generate response
            inputs = self.tokenizer(prompt, return_tensors="pt")
            outputs = self.model.generate(
                inputs["input_ids"],
                attention_mask=inputs.get("attention_mask"),
                max_new_tokens=150
            )
            response = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            
            # Since small models struggle with strict JSON formatting, we catch JSON decoding errors
            # and fallback to a heuristic rule-based template if the LLM output is malformed.
            parsed = json.loads(response)
            if not isinstance(parsed, dict):
                raise ValueError("Parsed JSON is not a dictionary.")
            return parsed
        except Exception as e:
            print(f"LLM generated invalid JSON or failed parsing: {e}")
            print("Falling back to heuristic planning.")
            return self._fallback_plan(query)

    def _fallback_plan(self, query: str) -> Dict[str, Any]:
        """A heuristic fallback ensuring the pipeline always receives valid JSON plans."""
        return {
            "goal": query,
            "subtasks": [
                {"id": 1, "description": f"Retrieve context for: {query}", "type": "retrieve"},
                {"id": 2, "description": "Reason over the retrieved context", "type": "reason"},
                {"id": 3, "description": "Formulate final answer", "type": "execute"}
            ],
            "required_tools": ["retriever"],
            "notes": "Generated by LLM fallback due to output formatting limitations"
        }
